version: '3.8'

services:
   postgres:
      image: postgres:latest
      container_name: postgres_hypequeue
      environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_DB: ${POSTGRES_DB}
      ports:
         - "5432:5432"
      restart: unless-stopped   
      volumes:
         - hypequeue_postgres_data:/var/lib/postgresql/data

volumes:
    hypequeue_postgres_data:
              